name: equations_solver
description: An equation solving application written in Dart

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/equatable
  equatable: ^2.0.2

  equations:
    path: ../../

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.0.0

  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.22.0

  # https://pub.dev/packages/google_fonts
  google_fonts: ^2.1.0

  # https://pub.dev/packages/hydrated_bloc
  hydrated_bloc: ^7.0.0

  # https://pub.dev/packages/intl
  intl: ^0.17.0

  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.2

dev_dependencies:

  # https://pub.dev/packages/bloc_test
  bloc_test: ^8.0.1

  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/golden_toolkit
  golden_toolkit: ^0.9.0

  # https://pub.dev/packages/test
  test: ^1.16.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - google_fonts/
