name: equations_solver
description: An equation solving application written in Dart

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equations:
    path: ../../

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.0

  # https://pub.dev/packages/go_router
  go_router: ^3.1.0

  # https://pub.dev/packages/intl
  intl: ^0.17.0

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.15.2

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  generate: true

  fonts:
    - family: Lato
      fonts:
      - asset: fonts/Lato-Black.ttf
      - asset: fonts/Lato-Bold.ttf
      - asset: fonts/Lato-Italic.ttf
      - asset: fonts/Lato-Light.ttf
      - asset: fonts/Lato-Regular.ttf
      - asset: fonts/Lato-Thin.ttf

  uses-material-design: true