name: equations_solver
description: An equation solving application written in Dart

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.0
  google_fonts: ^2.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  equations:
    path: ../../
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - google_fonts/