name: equations_solver
description: An equation solving application written in Dart

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equations:
    path: ../../

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.0.3

  # https://pub.dev/packages/google_fonts
  google_fonts: ^2.3.2

  # https://pub.dev/packages/intl
  intl: ^0.17.0

dev_dependencies:
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.15.2

  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/golden_toolkit
  golden_toolkit: ^0.13.0

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - google_fonts/
