name: equations_solver
description: An equation solving application written in Dart

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc_test: ^8.0.0

  equatable: ^2.0.0

  equations:
    path: ../../

  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^0.20.0-nullsafety.3

  google_fonts: ^2.0.0

  hydrated_bloc: ^7.0.0

  intl: ^0.17.0

  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - google_fonts/