name: equations
description: An equation solving library written in Dart which also works with complex numbers and fractions.
version: 3.2.0
repository: https://github.com/albertodev01/equations
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/fraction
  fraction: ^4.0.1

  # https://pub.dev/packages/petitparser
  petitparser: ^4.4.0

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.1.0

  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: ^4.10.1

  # https://pub.dev/packages/lints
  lints: ^1.0.1

  # https://pub.dev/packages/test
  test: ^1.20.1
  