name: equations
description: An equation solving library written in Dart. It also works with complex numbers and fractions.
version: 2.0.1
repository: https://github.com/albertodev01/equations
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  fraction: ^2.0.1
  petitparser: ^4.0.2

dev_dependencies:
  coverage: ^1.0.2
  test: ^1.16.8