name: equations
description: An equation solving library written in Dart. It also works with complex numbers and fractions!
version: 1.0.1
repository: https://github.com/albertodev01/dart_equations
homepage: https://fluttercompletereference.com/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  fraction: ^1.2.1
  math_expressions: ^2.0.0

dev_dependencies:
  test: ^1.14.6