name: equations_ci

on:
  push:
    paths:
      - "lib/**"
      - "test/**" 
      - ".github/workflows/equations_ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.12.0
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings lib

      - name: Run tests
        run: dart test --coverage=coverage test && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 95
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}